#ifndef HARDWAREPROFILE_H_INCLUDED
#define HARDWAREPROFILE_H_INCLUDED

#define HAP_SAFETY   GPIO_NUM_2
#define HAP_SIGNAL   GPIO_NUM_6
#define HAP_APPROVAL GPIO_NUM_3

#define MB_UART_TXD GPIO_NUM_21
#define MB_UART_RXD GPIO_NUM_20
#define MB_DERE     GPIO_NUM_7

#define HAP_LED_RUN    GPIO_NUM_8
#define HAP_LED_ACTIVE GPIO_NUM_9


#define I2C_SDA GPIO_NUM_0
#define I2C_SCL GPIO_NUM_1

#endif